from .data_loader_cifar10 import get_data_loaders as data_loader_cifar10
from .data_loader_fashionmnist import get_data_loaders as data_loader_fashion_mnist
from .data_loader_imagenet import get_data_loaders as data_loader_imagenet
from .data_loader_mnist import get_data_loaders as data_loader_mnist
from .get_dataloader import get_dataloader
